module.exports = {
  USER_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLOCKED: 'BLOCKED',
    DELETED: 'DELETED',
  },
  APPOINTMENT_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    RESCHEDULED: 'RESCHEDULED',
    MISSED: 'MISSED',
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PAID: 'PAID',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
  },
  CONSULTATION_TYPE: {
    VIDEO: 'VIDEO',
    AUDIO: 'AUDIO',
    CHAT: 'CHAT',
    IN_PERSON: 'IN_PERSON',
    INSTANT: 'INSTANT',
    FOLLOWUP: 'FOLLOWUP',
  },
};
